Ancien portail/Marketplace/WillemseFranceMP/Controllers/ProduitsController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WillemseFranceMP.Models;

namespace WillemseFranceMP.Controllers
{
    
    // Ce controller gère les différentes fonctionnalités produits
    [Authorize]
    public  class ProduitsController : Controller
    {
        private ProduitDbOracleContext db = new ProduitDbOracleContext();
        private ApplicationDbOracleContext dbA = new ApplicationDbOracleContext();
        private CommandeDbOracleContext dbc = new CommandeDbOracleContext();
        private Parametres p = new Parametres();
        private UtilNotifications notif = new UtilNotifications();
        private string dossiersFournisseurs, ektas;

        public ProduitsController()
        {
            this.dossiersFournisseurs = p.DossiersFournisseurs;
            this.ektas = p.ektas;
        }


        // Récupérer l'identité de l'utilisateur connecté
        private ApplicationUser CurrentUser
        {
            get
            {
                string currentUserId = User.Identity.GetUserId();
                return dbA.Users.FirstOrDefault(x => x.Id == currentUserId);
            }
        }


        // La page d'accueil du catalogue de produits (liste tous les produits d'un fournisseur)
        [HttpGet]
        [Authorize(Roles = "Utilisateur")]
        public ActionResult Index(string currentFilter,string recherche,int ? page)
        {
            if (ApplicationUser.estEnAttente(CurrentUser)) 
                return RedirectToAction("Attente");
            if (recherche != null)
            {
                page = 1;
            }
            else
            {
                recherche = currentFilter;
            }
            ViewBag.CurrentFilter = recherche;
            var produits = db.Produits.Where(d => d.IdFou == CurrentUser.IdFou && d.ACTIVE == "Oui").OrderByDescending(x => x.DateMod).ToList();
            if (!string.IsNullOrEmpty(recherche)&&!string.IsNullOrWhiteSpace(recherche))
            {
                produits = produits.Where(d => ((d.IdFou == CurrentUser.IdFou) && (d.CodProFou.Equals(recherche)))).ToList() ;
            }
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(produits.ToPagedList(pageNumber,pageSize));
        }


        // Page en attente de validation du compte par un administrateur
        [HttpGet]
        [Authorize(Roles = "Utilisateur")]
        public ActionResult Attente()
        {
             return View("AttenteValidation");
        }


        // GET: Produits/Details/id (détails d'un produit)
        public ActionResult Details(int? id)
        {
            // Test privilèges modification
            if (ApplicationUser.estAdmin(CurrentUser) || ApplicationUser.estSuperAdmin(CurrentUser))
            {
                ViewBag.Message = "a";
                if (User.IsInRole("Super"))
                {
                    ViewBag.Message = "p";
                }
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            // Règles de sécurité : eviter qu'un fournisseur ne consulte des produits qui lui appartiennent pas
            if (!ApplicationUser.estAdmin(CurrentUser) && !ApplicationUser.estSuperAdmin(CurrentUser) && (produit.IdFou != CurrentUser.IdFou))
                return HttpNotFound();

            produit.CatArborIn = Arb4.libelleArbor(produit.CodeSecteur);
            produit.PerPlant = FormatDonnees.getCheckboxValues(produit.PerPlant, 1);
            produit.PerFlo = FormatDonnees.getCheckboxValues(produit.PerFlo, 1);
            produit.PerSemis = FormatDonnees.getCheckboxValues(produit.PerSemis, 1);
            produit.PerRecolte = FormatDonnees.getCheckboxValues(produit.PerRecolte, 1);
            produit.PerLiv = FormatDonnees.getCheckboxValues(produit.PerLiv, 1);
            produit.TypSol = FormatDonnees.getCheckboxValues(produit.TypSol, 2);
            produit.Exposition = FormatDonnees.getCheckboxValues(produit.Exposition,3);
            produit.TypUtil = FormatDonnees.getCheckboxValues(produit.TypUtil, 4);
            ViewBag.TYPUSER = ApplicationUser.estAdmin(CurrentUser);
            return View(produit);
        }


        // Gère les listes déroulantes dynamiques de l'arborescence produit
        // Niveau 1
        public ActionResult Arb1List()
        {
            IQueryable arb1 = Arb1.GetArb1();
                if (HttpContext.Request.IsAjaxRequest())
                {
                    return Json(new SelectList(
                                arb1,
                                "Arb1Code",
                                "Arb1Name"), JsonRequestBehavior.AllowGet
                                );

                }              
            return View(arb1);         
        }
        // Niveau 2
        public ActionResult Arb2List(string Arb1Code)
        {
            IQueryable arb2 = Arb2.GetArb2(Arb1Code.Replace("xxx", "&"));
            {
                if (HttpContext.Request.IsAjaxRequest())
                {
                    return Json(new SelectList(arb2,"Arb2ID","Arb2Name"), JsonRequestBehavior.AllowGet);
                }
            }
            return View(arb2);
        }
         // Niveau 3
        public ActionResult Arb3List(string Arb1Code,  string Arb2Code)
        {
            IQueryable arb3 = Arb3.GetArb3(Arb1Code.Replace("xxx", "&"), Arb2Code.Replace("xxx","&"));
            {
                if (HttpContext.Request.IsAjaxRequest())
                {
                    return Json(new SelectList(arb3, "Arb3ID", "Arb3Name"), JsonRequestBehavior.AllowGet);
                }

            }
            return View(arb3);
        }
        // Niveau 4
        public ActionResult Arb4List(string Arb1Code, string Arb2Code, string Arb3Code)
        {
            IQueryable arb4 = Arb4.GetArb4(Arb1Code.Replace("xxx", "&"), Arb2Code.Replace("xxx", "&"), Arb3Code.Replace("xxx", "&"));
            {
                if (HttpContext.Request.IsAjaxRequest())
                {
                    return Json(new SelectList(arb4, "Arb4ID", "Arb4Name"), JsonRequestBehavior.AllowGet);
                }
            }
            return View(arb4);
        }
        
        // Formulaire de création d'un nouveau produit 
        [Authorize(Roles = "Utilisateur")]
        public ActionResult Create()
        {
            if (ApplicationUser.estEnAttente(CurrentUser))
                return RedirectToAction("Attente");
            return View();
        }

        // POST: Produits/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Utilisateur")]
        public ActionResult Create(CreateProduitViewModel model,string[] Perplant,string[] Perflo,string[] Perrec, string[] Persem, string[] Perliv, string[] Expo, string[] Typutil, string[] Typsol) {
            Produit produit;       
            if (ModelState.IsValid)
            {
                string idfou = CurrentUser.IdFou;
                string sigimg = CurrentUser.Valzn1;
                // Test de l'unicité du code produit fournisseur pour chaque fournisseur 
                produit = db.Produits.SingleOrDefault(u => (u.IdFou == idfou && u.CodProFou == model.CodProFou));
                if (produit == null)
                {
                    produit = new Produit();
                }
                else
                {
                    ModelState.AddModelError("CodProFou", "Vous disposez déjà d'un produit avec le code fournisseur : " + model.CodProFou);
                    return View(model);
                }
                string fich1 = null; string fich2 = null; string fich3 = null; string fich4 = null; string fich5 = null; string fich6 = null;
                string fichpdf = null;
                string codeSect = "0";
                NewArbor sect = new NewArbor();
                string sect1 = model.Arb1;
                string sect2 = model.Arb2;
                DirectoryInfo res = new DirectoryInfo(@ektas); // l'image est  copiée dans \\Rho pour traitement automatique
                if (string.IsNullOrEmpty(sect1) || string.IsNullOrWhiteSpace(sect1))
                {
                    sect1 = sect2 = "";
                }
                if (string.IsNullOrEmpty(sect2) || string.IsNullOrWhiteSpace(sect2))
                {
                    sect2 = "";
                }
                sect = db.NewArbors.FirstOrDefault(u => (u.Secteur == sect1 && u.SousSecteur == sect2));
                if (sect != null)
                {
                    codeSect = sect.CodeSecteur;
                }
                else
                {
                    codeSect = "-1";
                }
                string pplant = null; string pflo = null; string psemis=null; string prec = null; string pliv = null;  string typsol = null;
                string expo = null; string typutil = null;
                if (model.ImgPrinc != null && model.ImgPrinc.ContentLength>0)
                {
                    if(!String.IsNullOrEmpty(sigimg))
                        fich1 = sigimg + "-" + Path.GetFileName(model.ImgPrinc.FileName) ;
                    else
                        fich1 = Path.GetFileName(model.ImgPrinc.FileName);
                    var path_f1 = Path.Combine(Server.MapPath(dossiersFournisseurs + "/" + idfou + "/Images"), fich1);
                    model.ImgPrinc.SaveAs(path_f1);
                    System.IO.File.Copy(path_f1, Path.Combine(@ektas, fich1), true);
                }
                if (model.ImgSecond1 != null && model.ImgSecond1.ContentLength > 0)
                {

Ancien portail/Marketplace/WillemseFranceMP/Views/Shared/AttenteValidation.cshtml
@{
    ViewBag.Title = "Bienvenue - Portail fournisseur ";
}

<h2 style="color:darkgreen;">   Bienvenue sur notre portail fournisseur&nbsp;!</h2>
<div class="alert alert-info">

   <strong>Vous êtes en attente de validation par nos services !</strong> Vous recevrez un mail de confirmation avec votre identifiant fournisseur.

</div>

Ancien portail/Marketplace/WillemseFranceMP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr-fr">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Willemse France</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-toggle2.css" rel="stylesheet" />   
    <link href="~/Content/bootstrap-toggle2.min.css" rel="stylesheet" />    
    <link rel="stylesheet" type="text/css" href="/jquery.datetimepicker.css" />
    <script src="/jquery.js"></script>
    <script src="/build/jquery.datetimepicker.full.min.js"></script>
    <link rel="icon" href="http://www.willemsefrance.fr/skin/frontend/willemseV2/default/images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="http://www.willemsefrance.fr/skin/frontend/willemseV2/default/images/favicon.ico" type="image/x-icon" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" style="height:7%;padding-left:4%;padding-right:4%">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand" style="margin:0">
                    <img src="~/ImagesSite/Logo.png" alt="Logo WillemseFrance"  class="img-responsive"/>
                    
                </a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
            <div class="navbar-default navbar-collapse" id="myNav" style="margin-top:15px">
                <ul class="nav navbar-nav" style="margin-top:10px">
                    <li>&nbsp;
                        <b >
                            @Html.ActionLink("Accueil", "Index", "Home", routeValues: null, htmlAttributes: new { style = "color:darkslategrey" })
                        </b>&nbsp;

                    <li>&nbsp;
                        <b>
                            @Html.ActionLink("Mon catalogue", "Index", "Produits", routeValues: null, htmlAttributes: new { style = "color:darkslategrey" })
                        </b>&nbsp;

                    <li>&nbsp;
                        <b>
                            @Html.ActionLink("FAQ", "About", "Home", routeValues: null, htmlAttributes: new { style = "color:darkslategrey" })
                        </b>&nbsp;
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="panel btn-group btn-group-justified" style="text-align:center;">
                @if (ViewBag.Message == "p" || ViewBag.Message == "a")
            {

                    @Html.ActionLink("Fournisseurs", "../Admin/Index", routeValues: null, htmlAttributes: new {@class= "btn btn-default", style = "color:darkslategrey", id="pageFournisseurs" })
                    @Html.ActionLink("Nouveaux comptes", "../Admin/ValidFou", routeValues: null, htmlAttributes: new { @class = "btn btn-default", style = "color:darkslategrey", id = "pageComptes" })
                    @Html.ActionLink("Validation des Produits", "../Admin/ValidPro", routeValues: null, htmlAttributes: new { @class = "btn btn-default", style = "color:darkslategrey", id = "pageProduits" })
                    @Html.ActionLink("Export vers l'ERP", "../Admin/EnvoieERP", routeValues: null, htmlAttributes: new { @class = "btn btn-default", style = "color:darkslategrey", id = "pageExport" })
                    if (ViewBag.Message == "p")
                    {
                        @Html.ActionLink("Suivi de commandes", "Index", "Commandes", routeValues: null, htmlAttributes: new { @class = "btn btn-default", style = "color:darkslategrey", id = "pageCommandes" })

                        @Html.ActionLink("Administrateurs", "../Admin/Administrateurs", routeValues: null, htmlAttributes: new { @class = "btn btn-default", style = "color:darkslategrey", id = "pageAdmins" })
            
                        @Html.ActionLink("Parametres", "../Admin/Parametrage", routeValues: null, htmlAttributes: new { @class = "btn btn-default", style = "color:darkslategrey", id = "pageParametres" })
                    }
                    else
                    {
                        @Html.ActionLink("Suivi de commandes", "Index", "Commandes", routeValues: null, htmlAttributes: new { @class = "btn btn-default", style = "color:darkslategrey", id = "pageCommandes" })
                    }
                }
        </div>

        @RenderBody()
    </div>
    <br /><br />
    <footer class="navbar-fixed-bottom" style="height:4%;background-color:white">
        <p style="margin-left:50px">&copy; @DateTime.Now.Year - Portail fournisseur - Willemse France</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.intellisense.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/respond.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>