Ancien portail/Marketplace/WillemseFranceMP/Controllers/FichierProduitsController.cs
using Microsoft.AspNet.Identity;
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WillemseFranceMP.Models;

namespace WillemseFranceMP.Controllers
{
    // Ce controller gère tous les traitements de fichiers et dossiers
    [Authorize(Roles = "Utilisateur")]
    public class FichierProduitsController : Controller
    {
        private ProduitDbOracleContext db = new ProduitDbOracleContext();
        private ApplicationDbOracleContext dbA = new ApplicationDbOracleContext();
        private ImportExcelFile FicPro = new ImportExcelFile();
        private Parametres p = new Parametres();
        UtilNotifications notif = new UtilNotifications();
        private string dossiersFournisseurs;
        private string appData;

        public FichierProduitsController()
        {
            this.dossiersFournisseurs = p.DossiersFournisseurs;
            this.appData = p.appData;
        }

        private ApplicationUser CurrentUser
        {
            get
            {
                string currentUserId = User.Identity.GetUserId();
                return dbA.Users.FirstOrDefault(x => x.Id == currentUserId);
            }
        }
        public ActionResult Index()
        {
            if (ApplicationUser.estEnAttente(CurrentUser))
                return RedirectToAction("Attente", "Produits");
            return View();
        }

        // Permet de télécharger un modèle de fichiers produits dans un document excel 
        public FileResult Download(string id)
        {
            if (!string.IsNullOrEmpty(id)&&id.Equals("Pro"))
            {
              string  filename = "MP_" + CurrentUser.Societe.Replace(" ",string.Empty) + "_Produits.xlsx";
              return File(Path.Combine(Server.MapPath(appData),p.modeleProduits), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", filename);
            }
            return null;
        }

        // Permet de télécharger un modèle de fichiers offres dans un document excel 
        // tout en considérant les références produit fournisseur et la désignation commerciale des produits enregistrés
        public FileResult DownloadOffExcel(string id)
        {
            if (!string.IsNullOrEmpty(id) && id.Equals("Off"))
            {
                string sourcepath = Path.Combine(Server.MapPath(appData), p.modeleOffres);
                string filename = "MP_" + this.CurrentUser.Societe.Replace(" ",string.Empty) + "_Offres.xlsx";
                string destpath = Server.MapPath(dossiersFournisseurs +"/" + CurrentUser.IdFou + "/" + filename);
                System.IO.File.Copy(sourcepath, destpath, true);
                // On peut utiliser l'appel asynchrone 
                this.FicPro.CreateExcelFileOff(destpath, CurrentUser.IdFou);
                return File(destpath, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", filename);
            }
            return null;

        }


        // Permet de traiter un fichier de produits chargé par un fournisseur et crée un fichier de rapports d'erreurs
        [HttpPost]
        public ActionResult GenereFicPro(FicheProduitViewModel model)
        {
            DataTable dtResult = null;
            int nbErrors = 0; 
            if (ModelState.IsValid)
            {
                if (model.FicPro != null && model.FicPro.ContentLength > 0)
                {
                    try
                    {
                        string filename = "MP_" + CurrentUser.Societe.Replace(" ",string.Empty) + "_Produits.xlsx";
                        string filePath = Server.MapPath(dossiersFournisseurs + "/" + CurrentUser.IdFou + "/" + filename);
                        model.FicPro.SaveAs(Path.Combine(Server.MapPath(dossiersFournisseurs + "/" + CurrentUser.IdFou), filename));   
                        dtResult = FicPro.ConvertExcelToDataTable(filePath, 1);
                        nbErrors = FicPro.checkFile(dtResult, Server.MapPath(dossiersFournisseurs + "/" + CurrentUser.IdFou), CurrentUser.IdFou, CurrentUser.Valzn1, 1);
                        System.Threading.Thread.Sleep(1000);
                        notif.MailAdmins(CurrentUser.IdFou, CurrentUser.Societe, CurrentUser.Nom, CurrentUser.Prenom);
                        if (nbErrors > 0)
                            return RedirectToAction("EtatChargement", new { status = 4 });
                    }
                    catch (Exception e)
                    {
                        Console.Out.WriteLine(e.StackTrace);
                        return RedirectToAction("EtatChargement", new { status = -1 });
                    }
                    
                    return RedirectToAction("EtatChargement", new { status = 1 });
                }
                
            }
            return View("Index");
        }


        // Permet de traiter un fichier offres chargé par un fournisseur et créer un fichier de rapports d'erreurs
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GenereFicOff(FicheProduitViewModel model)
        {
            DataTable dtResult = null;
            int nbErrors = 0;
            if (ModelState.IsValid)
            {
                if (model.FicPro != null && model.FicPro.ContentLength > 0)
                {
                    try
                    {
                        string filename = "MP_" + this.CurrentUser.Societe.Replace(" ",string.Empty) + "_Offres.xlsx";
                        string filePath = Server.MapPath(dossiersFournisseurs + "/" + CurrentUser.IdFou + "/" + filename);
                        model.FicPro.SaveAs(Path.Combine(Server.MapPath(dossiersFournisseurs + "/" + CurrentUser.IdFou), filename));
                        // On transforme le fichier excel dans une table pour récuperer les données 
                        // le 2ème paramètre : indique que le type de fichiers offres ou produits à traiter
                        dtResult = FicPro.ConvertExcelToDataTable(filePath, 2);
                        nbErrors = this.FicPro.checkFile(dtResult, Server.MapPath(dossiersFournisseurs + "/" + CurrentUser.IdFou), this.CurrentUser.IdFou, this.CurrentUser.Valzn1, 2);
                        System.Threading.Thread.Sleep(1000);
                        notif.MailAdmins(CurrentUser.IdFou, CurrentUser.Societe, CurrentUser.Nom, CurrentUser.Prenom);
                        if (nbErrors > 0)
                            return RedirectToAction("EtatChargement", new { status = 4 });
                    }
                    catch(Exception )
                    {
                        return RedirectToAction("EtatChargement", new { status = -1 });
                    } 
                    return RedirectToAction("EtatChargement", new { status = 2 });
                }
                
            }
            return View("Index");
        }

        // Gestion du chargement des images 
        // En entrée un fichier ZIP contenant toutes les images 
        // Dézippe le fichier pour récuperer les images et les copies dans le dossier Images du fournisseur
        public ActionResult ChargerImages(HttpPostedFileBase imagesZip)
        {
            if(ModelState.IsValid)
            {
                if(imagesZip!=null && imagesZip.ContentLength>0)
                {
                    try
                    {
                        string idfou = CurrentUser.IdFou;
                        string imgsig = CurrentUser.Valzn1;
                        string extractPath = Server.MapPath(dossiersFournisseurs + "/" + CurrentUser.IdFou + "/Images");
                        string zipPath = Path.Combine(extractPath, imagesZip.FileName);
                        string unzipPath = Path.Combine(extractPath, (Path.GetFileNameWithoutExtension(imagesZip.FileName)));
                        if (Directory.Exists(unzipPath)) Directory.Delete(unzipPath, true);
                        if (System.IO.File.Exists(zipPath)) System.IO.File.Delete(zipPath);
                        imagesZip.SaveAs(zipPath);
                        // Forcer à remplacer anciennes images:
                        using (var zip = ZipFile.OpenRead(zipPath))
                        {
                            foreach (ZipArchiveEntry e in zip.Entries)
                            {
                                e.ExtractToFile(Path.Combine(extractPath, imgsig + '-' + e.Name), true);
                                // copie dans répertoire ektas à traiter
                                System.IO.File.Copy(Path.Combine(extractPath, imgsig + '-' + e.Name), Path.Combine(@p.ektas, imgsig + '-' + e.Name), true);
                            }
                        }
                        System.IO.File.Delete(zipPath);
                        GestionErreurImage.ecrireRapport(Server.MapPath(dossiersFournisseurs + "/" + CurrentUser.IdFou), idfou);
                    }
                    catch (Exception  )
                    {
                        return RedirectToAction("EtatChargement", new { status = -1 });
                    }
                    return RedirectToAction("EtatChargement", new { status = 3 });

                }
                    
            }
            return View();
        }


        // Gestion du chargement des fiches infos PDF
        // En entrée un fichier ZIP contenant tous les documents 
        // Dézippe le fichier pour récuperer les fiches et les copies dans le dossier du fournisseur
        public ActionResult ChargerFiches(HttpPostedFileBase PdfZip)
        {
            if (ModelState.IsValid)
            {
                if (PdfZip != null && PdfZip.ContentLength > 0)
                {
                    try
                    {
                        string idfou = CurrentUser.IdFou;

Ancien portail/Marketplace/WillemseFranceMP/Views/FichierProduits/EtatChargement.cshtml
@{
    ViewBag.Title = "Etat Chargement Flux ";
}

<h2>Etat de chargement du fichier</h2>

<hr/>
 
@{
    if (ViewBag.IncorrectFile != null && ViewBag.IncorrectFile)
    {
        <div class="alert alert-danger">
            <strong>Erreur ! </strong> @ViewBag.StatusFile.
        </div>
    }
    else if (ViewBag.Error != null && ViewBag.Error)
    {
        <div class="alert alert-danger">
            <strong>Attention!</strong> @ViewBag.StatusFile.
        </div>
    }
    else
    {
        <div class="alert alert-success">
            <strong>Chargement réussi!</strong> @ViewBag.StatusFile.
        </div>
    }
}



<a href="#"><span class="glyphicon glyphicon-arrow-left"></span></a>
@Html.ActionLink("Retour", "Index")

Ancien portail/Marketplace/WillemseFranceMP/Views/FichierProduits/Index.cshtml
@model WillemseFranceMP.Models.FicheProduitViewModel


@{
    ViewBag.Title = "Fichiers de produits et offres";
    // Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 style="color:darkgreen">@ViewBag.Title</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-1.10.2.js")" type="text/javascript"></script>
<br />

<div class="panel panel-success ">
    <div class="panel-heading text-center">
        <h4> 
            <span class="badge" style="font-size:large">1</span> 
            Téléchargez nos modèles de fichiers
        </h4>
    </div>
</div>

    <div class="row">
        <div class="col-lg-6 text-center" style="margin-top:10px">
            <a class="btn btn-default btn-file" href="@Url.Action("Download",new { id = "Pro" })">
                <span  class="glyphicon glyphicon-import" role="button"></span>
                Téléchargez le modèle produits
            </a>        
        </div>
        <div class="col-lg-6 text-center" style="border-left:3px solid grey;margin-top:10px">
            <a class="btn btn-default btn-file" href="@Url.Action("DownloadOffExcel",new { id = "Off" })">
                <span class="glyphicon glyphicon-import" role="button"></span>
                Téléchargez le modèle offres
            </a>
        </div>
    </div>
<br/>
<div class="panel panel-success">
    <div class="panel-heading text-center">
        <h4> 
        <span class="badge" style="font-size:large">2</span> 
        Chargez votre fichier
        </h4>
    </div>
</div>
<p class="text-center text-warning"><b>Pour être valides, les fichiers doivent respecter nos modèles.</b></p>
<p class="text-center text-warning"><b>Veuillez respecter les noms et l'ordre des <mark>colonnes(champs)</mark> dans votre fichier.&nbsp; </b></p>
<p class="text-center text-warning"><b>Veuillez respecter les noms et l'ordre des <mark>feuilles</mark> dans votre fichier.</b></p>
<p class="text-center text-danger"><b>ATTENTION! La suppression des produits se fait dans le portail et non pas dans le fichier.</b></p>  
   
<div class="row">
    <div class="col-lg-6 text-center" style="margin-top:10px">
        @using (Html.BeginForm("GenereFicPro", "FichierProduits", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
        {
           <label class="btn btn-default btn-file" style="height:35px">
               <span class="glyphicon glyphicon-export"></span>               
               Chargez un fichier de produits
               @Html.AntiForgeryToken()
               @Html.ValidationSummary("", new { @class = "text-danger" })
               @Html.TextBoxFor(m => m.FicPro, new { type = "file", accept = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", style = "display:none" })
               @Html.ValidationMessageFor(m => m.FicPro, "", new { @class = "text-danger" })
            </label>
            <input type="submit" value="ok" class="btn btn-default btn-file"/>
        }
    </div>
    <div class="col-lg-6 text-center" style="border-left:3px solid grey;margin-top:10px">
        @using (Html.BeginForm("GenereFicOff", "FichierProduits", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
        {
            <label class="btn btn-default btn-file" style="height:35px">
                <span class="glyphicon glyphicon-export"></span>
                Chargez un fichier d'offres
                @Html.AntiForgeryToken()
                @Html.ValidationSummary("", new { @class = "text-danger" })
                @Html.TextBoxFor(m => m.FicPro, new { type = "file", accept = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", style = "display:none" })
                @Html.ValidationMessageFor(m => m.FicPro, "", new { @class = "text-danger" })
            </label>
            <input type="submit" value="ok" class="btn btn-default btn-file" />
        }
    </div>
</div>
<br/>
<div class="panel panel-success ">
    <div class="panel-heading text-center">
        <h4> 
        <span class="badge"style="font-size:large">3</span> Rapport d'erreurs
        </h4>
    </div>
</div>
<p class="text-center text-warning"> 
    <b> Ce journal d'erreurs est le rapport sur l'état de chargement de votre dernier fichier.</b> 
</p>
<div class="row">
    <div class="col-lg-6 text-center" style="margin-top:10px">
        <a class="btn btn-default btn-file" href="@Url.Action("RapportErreur",new { id = "Pro" })">
            <span class="glyphicon glyphicon-import" role="button"></span>
            Rapport d'erreurs fichier produits
        </a>
    </div>
    <div class="col-lg-6 text-center" style="border-left:3px solid grey;margin-top:10px">
        <a class="btn btn-default btn-file" href="@Url.Action("RapportErreur",new { id = "Off" })">
            <span class="glyphicon glyphicon-import" role="button"></span>
            Rapport d'erreurs fichier Offres
        </a>
    </div>
</div>
 <br/>
<div class="panel panel-success ">
    <div class="panel-heading text-center">
        <h4> 
        <span class="badge"style="font-size:large">4</span> 
        Chargement d'images
        </h4>
    </div>
</div>
<p class="text-center text-warning"><b> Utilisez un dossier compressé ZIP pour charger les <mark>images</mark> de vos produits.</b></p>
<p class="text-center text-warning"><b> Les noms de fichiers de vos images doivent être les mêmes que ceux indiqués dans le fichier produits, par exemple "123.jpg"</b></p>
<div class="row">
    <div class="col-lg-6">
          <div class="form-inline text-center"style="margin-top:10px">
                @using (Html.BeginForm("ChargerImages", "FichierProduits", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data"}))
                {
                    <label class="btn btn-default btn-file" style="height:35px">
                        <span class="glyphicon glyphicon-export"></span>
                        Charger un fichier zip d'images
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    <input type="file" name="ImagesZip" accept=".zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed" required style="display:none" />
                    </label>
                    <input type="submit" value="ok" class="btn btn-default btn-file" />
                }
            </div>
    </div>
    <div class="col-lg-6 text-center"style="border-left:3px solid grey;margin-top:10px">
        <a class="btn btn-default btn-file" href="@Url.Action("RapportErreur",new { id = "Img" })">
            <span class="glyphicon glyphicon-import" role="button"></span>
            Rapport d'erreurs fichier Images
        </a>
    </div>
</div>



<br />
<div class="panel panel-success ">
    <div class="panel-heading text-center">
        <h4>
            <span class="badge" style="font-size:large">5</span>
            Chargement de fiches PDF
        </h4>
    </div>
</div>
<p class="text-center text-warning"><b> Utilisez un dossier compressé ZIP pour charger les <mark>Fiches PDF</mark> de vos produits.</b></p>
<p class="text-center text-warning"><b> Les noms des fichiers doivent être les mêmes que ceux indiqués dans le fichier produits, par exemple "ABC.pdf" </b></p>
<div class="row">
    <div class="col-lg-6">
        <div class="form-inline text-center" style="margin-top:10px">
            @using (Html.BeginForm("ChargerFiches", "FichierProduits", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                <label class="btn btn-default btn-file" style="height:35px">
                    <span class="glyphicon glyphicon-export"></span>
                    Charger un fichier zip
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    <input type="file" name="PdfZip" accept=".zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed" required style="display:none" />
                </label>
                    <input type="submit" value="ok" class="btn btn-default btn-file" />
            }
        </div>
    </div>
    <div class="col-lg-6 text-center" style="border-left:3px solid grey;margin-top:10px">
        <a class="btn btn-default btn-file" href="@Url.Action("RapportErreur",new { id = "Pdf" })">
            <span class="glyphicon glyphicon-import" role="button"></span>
            Rapport d'erreurs fichier PDF
        </a>
    </div>
</div>

<br/>
<div class="panel panel-success ">
    <div class="panel-heading text-center">
    <h4> 
        <span class="badge"style="font-size:large">6</span> 
        Votre Catalogue en Fichier CSV
        </h4>
    </div>
</div>

<div class="row">
    <div class="col-lg-6 text-center" style="margin-top:10px">
        <a class="btn btn-default btn-file" href="@Url.Action("chargerBDProduits")">
            <span class="glyphicon glyphicon-import" role="button"></span>
            Téléchargez tous vos Produits dans un Fichier CSV
        </a>
    </div>
    <div class="col-lg-6 text-center" style="border-left:3px solid grey;margin-top:10px">
        <a class="btn btn-default btn-file" href="@Url.Action("chargerBDOffres")">
            <span class="glyphicon glyphicon-import" role="button"></span>
            Téléchargez toutes vos Offres dans un Fichier CSV
        </a>
    </div>
</div>
<br /><br /><br />

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

Ancien portail/Marketplace/WillemseFranceMP/Views/FichierProduits/TestExcel.cshtml
@model IEnumerable<WillemseFranceMP.Models.TestView>
    
@using System.Data
@using WillemseFranceMP.Controllers.Helpers


@{
    ViewBag.Title = "Le fichier généré";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>
<table class="table table-hover">
    <tr>
        <th style="color:darkgreen;">Fournisseur</th>
        <th style="color:darkgreen;">Code Produit</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.CodPro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idfou)
            </td>
        </tr>
    }

</table>